### ISSUE TITLE
addChild is not a function

### ISSUE THREAD

**Issue by cdubant** [zdy1988/vue-jstree#11]
Hi Zhu,

It appears that if I take the same example as in the documentation, I'm not able to addChild on a node.

![image](https://user-images.githubusercontent.com/12911253/34253070-6299b92a-e646-11e7-89c0-0b068e655e17.png)

Node editing and deletion works fine but I'm afraid I don't get addChild to work properly, the exact error message is "Uncaught TypeError: this.editingNode.addChild is not a function"

**Comment by zdy1988** [comment]
your vue-jstree version is 1.0.9 ?

**Comment by cdubant** [comment]
Yes it is, I saw that it was in the code for version 1.0.9 so I updated from 1.0.7 to 1.0.9.

I checked that my version was really 1.0.9 by checking the code of tree.vue and found the following

![image](https://user-images.githubusercontent.com/12911253/34257364-e2af79ac-e659-11e7-8afe-2a655baa9d83.png)

So I assume it should work but I don't understand why it doesn't.

**Comment by zdy1988** [comment]
How is editingNode  assigned !  

the editingNode  is it a tree node ?

**Comment by cdubant** [comment]
Like this

![image](https://user-images.githubusercontent.com/12911253/34257684-28fe7f1a-e65b-11e7-9214-0636727da0cb.png)

![image](https://user-images.githubusercontent.com/12911253/34257707-3ff78aa4-e65b-11e7-82c6-6db0769fb4f9.png)

**Comment by zdy1988** [comment]
data is tree node
data.model is tree node data
 'mvvm' should operating data 
so, try **editingItem.addChild**

**Comment by cdubant** [comment]
![image](https://user-images.githubusercontent.com/12911253/34258690-64cc6332-e65f-11e7-9b6f-14f3e208fa1d.png)

I already tried this !

**Comment by zdy1988** [comment]
i do not know why ! my example work fine ...

**Comment by skynet2** [comment]
Hi @cdubant ,
Just had the same problem. Basically the problem is in the way how you set your data. 
Looks like your tree data is updated outside of the library. 
Here is a quick fix that : 
1. Reference your tree with ref attribute, ex (ref="tree")
2. Set data with library method initializeData : 
```
      this.menu = [{
        text: "Root",
        value: "Root",
        id: getNewId(),
      }];
      this.$refs.tree.initializeData(this.menu)
```

cc @zdy1988

**Comment by ngdevc** [comment]
![image](https://user-images.githubusercontent.com/65579678/115173227-69f69280-a0f9-11eb-94d9-83364903c5bc.png)
![image](https://user-images.githubusercontent.com/65579678/115173250-767aeb00-a0f9-11eb-8408-a3e930ed94a6.png)

**Comment by ngdevc** [comment]
I'm getting an error like the above screen.
Let me know the reason and solution.

**Comment by SyadBabarAli** [comment]
> Hi Zhu,
> 
> It appears that if I take the same example as in the documentation, I'm not able to addChild on a node.
> 
> ![image](https://user-images.githubusercontent.com/12911253/34253070-6299b92a-e646-11e7-89c0-0b068e655e17.png)
> 
> Node editing and deletion works fine but I'm afraid I don't get addChild to work properly, the exact error message is "Uncaught TypeError: this.editingNode.addChild is not a function"

Just call this method and send tree variable
Example 
this.$refs.tree.initializeData(this.dataJsTree);

**Comment by UlugbekNG** [comment]
> this.$refs.tree.initializeData(this.menu)

Can you give some code examples, please.
