### ISSUE TITLE
TypeError: Cannot read property 'parentItem' of null

### ISSUE THREAD

**Issue by DMoN-dt** [zdy1988/vue-jstree#13]
There is some error on Drag'n'Drop:

`[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'parentItem' of null
vue.runtime.esm.js?ff9b:1713 TypeError: Cannot read property 'parentItem' of null
at VueComponent.eval (webpack-internal:///278:1:8400)`

here:
`var r=this;this.$nextTick(function(){r.draggedItem.parentItem.splice(r.draggedItem.index,1)})`

So nextTick seems to be called after onItemDragEnd...

If change to this:
`var r=this.draggedItem;this.$nextTick(function(){r.parentItem.splice(r.index,1)})`
then no errors anymore!

**Comment by zdy1988** [comment]
**thanks a lot!**
