### ISSUE TITLE
icon 

### ISSUE THREAD

**Issue by Erimons-chan** [zdy1988/vue-jstree#15]
how to change icon

**Comment by zdy1988** [comment]
set css class like this

```
"icon": "fa fa-warning icon-state-danger"
```

**Comment by Erimons-chan** [comment]
，get，thanks

发自我的 iPhone

**Comment by Erimons-chan** [comment]
how to add   "newKey":"value"   to  data ,when i add to the data ,but i cant find "newKey"
like:
loadData(oriNode, resolve){
          setTimeout(() => {
            let data = []
              data = [
                {
                  "text": "New Item 1...",
                  "newKey":'value'
                },
                {
                  "text": "New Item 2...",
                }
              ]
            resolve(data)
          }, 500)
        }

but   in the console:
A {…}
addChild:ƒ (e),
children:Array(2),
disabled:false,
icon:"",
id:2,
loading:false,
opened:true,
selected:false,
text:"New Item 1...",
value:"New Item 1...",
__ob__:Observer {value: A, dep: Dep, vmCount: 0} 

i didnt find the new one

**Comment by zdy1988** [comment]
兄弟，可以中文交流的

有两个属性可以指定text字段，和value字段，默认是字段是'text'和'value'

textFieldName | Boolean | 'text'
valueFieldName | Boolean | 'value'

如果你的value字段是newKey，可以设置

```
<v-jstree value-field-name="newKey" ...></v-jstree>
```
