### ISSUE TITLE
How to make leaf node in AJAX?

### ISSUE THREAD

**Issue by DAud-IcI** [zdy1988/vue-jstree#17]
When I load the tree dynamically, can I specify that it doesn't have any children? I tried to set `children` property to `false` or `[ ]`, but it didn't work:

    var leaf_lode = {
        text: 'some description',
        children: false,
        id: 'some id'
    };

**Comment by zdy1988** [comment]
see the example:

Async Loading

 [https://zdy1988.github.io/vue-jstree/](https://zdy1988.github.io/vue-jstree/)
