### ISSUE TITLE
Customizing problem!

### ISSUE THREAD

**Issue by zuxriddinkamalov** [zdy1988/vue-jstree#20]
I can't customizing! When I set the style it affects the height. How to set padding between items. 
![image](https://user-images.githubusercontent.com/28143150/36365684-6e1a25d2-156c-11e8-8d83-bd4ecad36930.png)
If you specify a padding, the script does not correctly calculate the height.

**Comment by zdy1988** [comment]
you can set tree item size , value : 'large' or '' or ''small'
