### ISSUE TITLE
Custom text variable doesn't work

### ISSUE THREAD

**Issue by pmatisko** [zdy1988/vue-jstree#21]
Hello,

if you don't use text field name "text", the item will not be shown in the tree. Please, make the correction in:

Tree Item.vue to this:

            initializeDataItem (item) {
                function Model(item, textFieldName, valueFieldName) {
                    this.id = item.id || ITEM_ID++
                    this['text'] = item[textFieldName] || ''
                    this['value'] = item[valueFieldName] || item[textFieldName]
                    this.icon = item.icon || ''
                    this.opened = item.opened || false
                    this.selected = item.selected || false
                    this.disabled = item.disabled || false
                    this.loading = item.loading || false
                    this.children = item.children || []
                }

**Comment by zdy1988** [comment]
thanks, version 1.0.11 fiexd this bug

**Comment by wdda** [comment]
Hi. I would like to be able to embed html in a textField for change color text. I added this in last pull request. Now this deleted from current version. Why?

Thanks!

**Comment by wdda** [comment]
@zdy1988 

my code:
`-            {{model.text}}
+            <span v-html="model.valueFieldName"></span>`

https://github.com/zdy1988/vue-jstree/commit/dc3c977ea986834d62a4d48c749fe311b390e16d
