### ISSUE TITLE
Async Loading

### ISSUE THREAD

**Issue by shpfive** [zdy1988/vue-jstree#25]
Please provide the option to directly set a leaf

maybe something like this ?
`handleAsyncLoad(oriParent, oriNode, oriItem) {
        var self = this
        if (this.async) {
          if (oriParent[0].loading) {
            this.async(oriNode, (data) => {
              if (data.length > 0) {
                for (let i in data) {
                  if(!data[i].isLeaf) {
                      data[i].children = [self.initializeLoading()]
                  }
                  var dataItem = self.initializeDataItem(data[i])
                  self.$set(oriParent, i, dataItem)
                }
              } else {
                oriNode.model.children = []
              }
            })
          }
        }
      },`

**Comment by zdy1988** [comment]
you mean the node is not a leaf , hide loading?

**Comment by zdy1988** [comment]
very good !  thanks !

i added it in 1.0.14
