### ISSUE TITLE
[Feature Request] Selective drag and drop

### ISSUE THREAD

**Issue by abernov** [zdy1988/vue-jstree#29]
To make a file browser based on your component,  drop should only work to a folder.

Can be added Data Item Optional Properties, like **dropEnable** ?

**Comment by zdy1988** [comment]
hi ! i added it in 1.0.16 !

selective drag and drop can set 'dragDisabled: true' and 'dropDisabled: true' , all default value is 'false'

**Comment by abernov** [comment]
Great job! Thank you.

Drag drop for file browser now work fine.

But there is problem with Root node [see on line editor with project hire](https://jsfiddle.net/abernov/8ak4a1rq/)

The root node is needed to drop files and folders to root.

How to do root node always "opened"?
How to delete "+" in it?
At start "opened" property does not work!

**Comment by abernov** [comment]
I made changes [in my code.](https://jsfiddle.net/abernov/8ak4a1rq/)

Added itemEvents / click.

Root node now work fine.

Questions:

1) openChildren()/ closeChildren() - changed all nested children! 
But only the current node children's should be changed!

2) How to hide "+/-" components - 
In my application they are clearly superfluous

3) How to open only Root node at start?

**Comment by zdy1988** [comment]
hi !

1. only changing the current node can set the "opened: true" in the current item data.

2 and 5 . set  "isLeaf: true" , when use **async**  load

3. set root node **"opened": true**  

4. try " no-dots"

**Comment by abernov** [comment]
try " no-dots"  - fine, please update docs

**Comment by zdy1988** [comment]
maybe a vue version change ,   " no-dots" and "noDots" work fine that before !

**Comment by abernov** [comment]
3) set root node "opened": true
vue is crashed!

[See my code.](https://jsfiddle.net/abernov/8ak4a1rq/)

Uncomment the line 
//          "opened", true,  //does not work

click Update at top left of the editor
and reload web-page with the editor!

see vue is crashed

**Comment by abernov** [comment]
used vue@2.5.16

**Comment by zdy1988** [comment]
haha , you are too careless !

"opened"      **,**          true

**Comment by abernov** [comment]
I see! Updated! Thanks

Two problem not solved, see project:

1) +/1 at begin off line
2) sort the tree before drop.  Can be added event **beforeDrop**?

After all, all the folders of the same level should be at the top, and the files should be followed (my be sorted alphabetically)

**Comment by zdy1988** [comment]
i think you need a event like **droped**, and you can get childrens from parent node , then sort it !

**Comment by abernov** [comment]
Many thanks!

I updated [my code.](https://jsfiddle.net/abernov/8ak4a1rq/)

Sorting works as it should!

Wishes
1) multiple select tree items by mouse click and ctrl-button
2) after drop, dropped item must be selected
3) fix css, that the lines end on the last node

**Comment by zdy1988** [comment]
1. about **ctrl + click** ,you can try

```
     <v-jstree :data="data">
       <template scope="_">
         <div style="display: inherit; width: 200px" @click.ctrl="customItemClickWithCtrl">
           <i :class="_.vm.themeIconClasses" role="presentation" v-if="!_.model.loading"></i>
           {{_.model.text}}
           <button style="border: 0px; background-color: transparent; cursor: pointer;" @click="customItemClick(_.vm, _.model, $event)"><i class="fa fa-remove"></i></button>
         </div>
       </template>
     </v-jstree>

     **scope** be replaced in the **vue@2.5.0+** , over **vue@2.5.0+** use **slot-scope**
```

2. I hope you can control freely ，maybe like

···
      itemDrop (node, item， draggedItem， e) {
         draggedItem.selected = true
         or
         draggedItem.selected = item.selected
      },
···

3. i publish new version to fix it

thank you !

**Comment by zdy1988** [comment]
and i see your code , I hope you understand ,

**node** is a vue object
**item** is the real data

so, operation data completes state switch.

**Comment by abernov** [comment]
2. it's still bad - several nodes become selected! Check code.

A method is needed to deselect all, or select only one node.
Of course I can write it by myself.

**Comment by abernov** [comment]
1. I will try your code.

But multi select by ctrl - is standard action.

will be well if property **multiple** can get this values:
- enabled
- disabled
- ctrlClick

**Comment by zdy1988** [comment]
@abernov , The affected child nodes can refer to this example.

```
      itemDrop (node, item， draggedItem， e) {
          this.$refs.tree.handleRecursionNodeChildren(draggedItem, item => {
            item.selected = item.selected
          })
      }
```

**Comment by zdy1988** [comment]
1.  **scope**  contains all the property you want

**vm** and **model**

**vm**  is the item vue object
**model**  is the real data

**Comment by abernov** [comment]
itemDrop (node, item， draggedItem， e) {
          this.$refs.tree.handleRecursionNodeChildren(**draggedItem**, item => {
            item.selected = item.selected
          })
      }

how to change **draggedItem** to the root item?

**Comment by zdy1988** [comment]
the root item can try **this.$refs.tree**

**Comment by abernov** [comment]
**this.$refs.tree** - Does not work! see code

**Comment by zdy1988** [comment]
try **handleRecursionNodeChilds**

**Comment by abernov** [comment]
this.$refs.tree.handleRecursionNodeChilds( this.$refs.tree,  item => {
            item.selected = false
      })
This code does not deselect all tree!

**Comment by zdy1988** [comment]
this.$refs.tree.**handleRecursionNodeChilds**(this.$refs.tree, **node** => {
**node.model**.selected =false
})

**Comment by abernov** [comment]
Thank you! Perfectly

**Comment by abernov** [comment]
ctrl - multiselect does not work.

Somewhere inside the default onclick is triggered

[my code hire](https://jsfiddle.net/abernov/8ak4a1rq/)

**Comment by zdy1988** [comment]
@click.ctrl="itemCtrlClick(_.vm,$event)"

 itemCtrlClick: function(node, e) {
     **e.stopPropagation()**
      node.model.selected =  true
//      alert("ctrl click : " + node.model.text)
 },

**Comment by abernov** [comment]
Thank you! Perfectly.
Question about performance.

this.$refs.tree.handleRecursionNodeChilds( this.$refs.tree,  node => {
            node.model.selected = false
      })

Passes through all nodes. And if in the tree are too many of nodes and nodes require processing?

But usually, selected nodes always is opened nodes (that you do not support, but it would be good if nodes were deselected if they are not visible)

For deselect, for performance, how to pass only through opened nodes?

**Comment by zdy1988** [comment]
about **this.$refs.tree**  , you can optionally pass in the node as long as its type is a node.

because MVVM is data-driven , so i manipulate the nodes by manipulating the data , its two-way binding allows me to easily access data and modify data. so i made this method.

but I think it's going to be very inefficient when I have more data.

And of course I can find a node in some way , such as **document.getElementById** , but it's not a vue object ,  when I need to modify the node data, I still have to find the data recursively.

so , if you want pass only through opened nodes

```
this.$refs.tree.handleRecursionNodeChilds( this.$refs.tree, node => {
if (node.model.opened) {
node.model.selected = false
}
})
```

or i already got a opened node 

```
this.$refs.tree.handleRecursionNodeChilds(yourOpenedNode, node => {
node.model.selected = false
})
```

**Comment by abernov** [comment]
this.$refs.tree.handleRecursionNodeChilds( this.$refs.tree, node => {
 **body of function**
})

all the same - passes through all nodes

if there are 1000 nodes and only 5 visible, body of this function will be called 1000 times, not 5 times!

Recursion is needed, which only passes through opened nodes and its children, and not go to children-children. 

Maybe of course I'm mistaken about performance.

**Comment by abernov** [comment]
[Bug on your example!](https://zdy1988.github.io/vue-jstree/)

when click top line **same but with checkboxes** also selected node **initially open**!

**Comment by zdy1988** [comment]
yes , @abernov , you are right !

i know it has performance problem when its has too many of nodes !

but I haven't found a good solution yet.

**maybe I can copy a one-dimensional array from the data to help us find the nodes when I initialize the tree !!!**

do you have any suggestions ?

**Comment by abernov** [comment]
Why not add a method

this.$refs.tree.handleRecursion**Opened**NodeChilds

and use it in vue-jstree, instead this.$refs.tree.handleRecursionNodeChilds

There are always not many open nodes - otherwise it's hard to look at the screen.

And closed nodes are not interesting to us at all, except Search action.

**Comment by zdy1988** [comment]
yes , i understand what you mean

and for easier control. i can reconstruct the method. just add a limit , like :

if  **body of function** return false ,  terminates the recursive child node.

**Comment by zdy1988** [comment]
1. In the case of a single select. 

such as a state in the secondary node is selected, but his parent node is closed, then I selected another, it has the same level to the parent node, then I must be the entire tree recursive, to set all other nodes to unselected

2. In the case of multiple select , its use batch select

i must use it to recurse all of the child nodes of  current node , set children nodes selected/unselected

3. In the case of multiple select , its not batch select

it doesn't use recursion at all.

so i can only open the method to you to choose.

**Comment by abernov** [comment]
1. It is necessary to do that there were no invisible nodes (which have closed parent) which have selected = true. 
If parent not opened then all children must have selected = false.

I do not understand why let to invisible children nodes to be selected.
I have never seen such an opportunity. This opportunity reduces performance

If we accept this, it is easily solved 2 and 3.

**Comment by abernov** [comment]
For performance i use this function

 deselectNodeChildren: function ( parent ) {
       this.$refs.tree.handleRecursionNodeChilds( parent,  node => {
          let prevsel = node.model.selected
          node.model.selected = false
          return **node.model.opened || prevsel**
       })
    },
