### ISSUE TITLE
Custom html for the items

### ISSUE THREAD

**Issue by lucafaggianelli** [zdy1988/vue-jstree#3]
Hi, very nice and useful lib!

Can I use custom html to render the tree items? for example using slots or whatever?
My problem is that I need a more complex item, that is, not just a text line but also images and other info, so I can't just customize the item with CSS.

Luca

**Comment by zdy1988** [comment]
Hi, Luca
I don't know how complex your tree is
If your tree item is very complex, I suggest you download the source code to rewrite the 'tree-item'

[vue-jstree/src/tree-item.vue](vue-jstree/src/tree-item.vue)

**Comment by lucafaggianelli** [comment]
Yes, it seems the only way to go!

**Comment by humblecoder** [comment]
I realize this is closed, but I would like something of this nature as well.  It would be nice to at least provide an editable floated right `folder-count` item of some sort.  Just to show the number of "files" inside a folder.

**Comment by lucafaggianelli** [comment]
If it can help you, see my fork, you can use a custom element:
https://github.com/lucafaggianelli/vue-jstree

**Comment by humblecoder** [comment]
@lucafaggianelli I don't see documentation for what you've added.

**Comment by lucafaggianelli** [comment]
Yes, no docs, just look at the sources or try this snippet:
``` vue
<v-jstree
            :data="activitiesTree"
            text-field-name="title"
            :show-checkbox="false"
            multiple
            allow-batch
            whole-row
            draggable
            @item-drop="onActivityMove">
          <template slot-scope="props">
            <my-custom-item
                :item="props.item.item"
                :children="props.item.children"
                :selected="props.selected"
                :open.sync="props.opened"
                :expenses="expenses"
                @edit="editActivity"
                @delete="deleteActivity">
            </my-custom-item>
          </template>
        </v-jstree>
```

**Comment by humblecoder** [comment]
@lucafaggianelli I may be missing something, but you seem to *require* a `custom-component`. Optional would be better.  Also, I have no concept of what your `custom item` should do as far as rendering folders, anchors, etc.  Looks like I'm going to have to go back.  Thanks anyway.

**Comment by zdy1988** [comment]
Hi ! @lucafaggianelli 
thanks for your idea, it's very good !

**Comment by humblecoder** [comment]
@zdy1988 does this mean you're going to incorporate this ability as an option?  🙏   It would really be nice to provide/display "meta" information on the folder items.
