### ISSUE TITLE
Dragging nested folders to "top level" proving impossible

### ISSUE THREAD

**Issue by humblecoder** [zdy1988/vue-jstree#30]
Hello, folder dragging and nesting in general work well -- until you need to drag a folder to the top (or root) level, then there is no drop point at which it works.  Please advise.

**Comment by abernov** [comment]
You can try to solve [this way](https://github.com/zdy1988/vue-jstree/issues/29)

By manually creating the Root node.

**Comment by humblecoder** [comment]
That was my first solution.  I don't like it, but I'll use it for now.  Any way to open it automatically?

**Comment by abernov** [comment]
Almost everything works [see hire](https://jsfiddle.net/abernov/8ak4a1rq/)

to change code

1) change code
2) click Update - top left corner of editor
3) reload editor page
