### ISSUE TITLE
How do we enable selection-related CSS?

### ISSUE THREAD

**Issue by humblecoder** [zdy1988/vue-jstree#31]
In the demos it appears that selected rows highlight grey.  However, using a vanilla install, this doesn't seem to be the case.  Full, disclosure, I am using Bootstrap, but I can't discern any collisions of any sort.  Please advise.

**Comment by humblecoder** [comment]
I did.  It didn't work.  There must be a Bootstrap collision somewhere.  Thanks.

**Comment by zdy1988** [comment]
this is done because the jstree UI does this.
maybe you can try single selected the tree node.
that is to get rid of the **multiple** choice properties.

**Comment by humblecoder** [comment]
Do you expose any aspect of `jstree` that would force refresh?  I ask, because I have a method that will set `icon` based on the currently selected folder.  Basically, I call `makeDefaultFolderStandOut(folder_list)` and recursively access each folder.  If the folder is `selected` then I set `icon = 'my_css_class'`.  I have this set to trigger when a folder is clicked.  However, it only works once.  I'm sure there is something about the internals that I'm not seeing, but I need the ability to force visual refresh at will.  Thoughts?

**Comment by zdy1988** [comment]
themeIconClasses () {
              return [
                  {'tree-icon': true},
                  {'tree-themeicon': true},
                  **{[this.model.icon]: !!this.model.icon},**
                  {'tree-themeicon-custom': !!this.model.icon}
              ]
          },

Why don't you set the icon by setting the node data?

**Comment by humblecoder** [comment]
@zdy1988 I do, but it doesn't refresh.  I'm outputting to  the `console`, and the values are correct, but the UI doesn't update accordingly.  Should I be making an additional method call?

**Comment by humblecoder** [comment]
@zdy1988 Using your new `template` works perfectly.  No doubt thanks to https://github.com/zdy1988/vue-jstree/issues/3.
