### ISSUE TITLE
Need to manually trigger click based on "id"

### ISSUE THREAD

**Issue by humblecoder** [zdy1988/vue-jstree#32]
I need the ability to manually trigger a click.  For example, on page load, I'd like to select the first item, and trigger its `item-click` event.  Please advise.

**Comment by zdy1988** [comment]
why are you do this ? 
do you want to set the initial state of the tree node?

**Comment by humblecoder** [comment]
Yes.  I want (based on pre-conditions) to select a node for "context".  Basically I select a folder, and "load" its contents.  Imagine I have a treeview on the left, and photo view on the right.  When I load the page, I want to select a specific folder, if available, and automatically load its contents.  I could fudge it by just running a random 'ID' from `children`, but I'd rather it apply in context.
