### ISSUE TITLE
Need the ability to receive "external" drop.

### ISSUE THREAD

**Issue by humblecoder** [zdy1988/vue-jstree#33]
I have an application where I simulate actual system folders.  I need the "treeview" to trigger a method that will accept the payload of the "drag-and-drop" event.  I'm not quite sure I understand your API on exposing events.  Would it be possible to expose `drop` and `dragend` in the same manner that you expose `item-click`?

**Comment by humblecoder** [comment]
Actually, it appears that it does accept drops, however, when I try to drop *exactly* on an item, I receive:  `Cannot read property 'contains' of null`.  That said, when I drop on a random area of the TreeView, it shows the payload, but I lose the ability to drop on a true target.

**Comment by zdy1988** [comment]
hi ! 
I don't understand what you mean.
after drop,  i test remove node , it work fine !
you can give me an example !

**Comment by humblecoder** [comment]
Imagine I have the treeview on the left and  a grid of photos on the right.  I need to drag and drop the photos to the treeview and "move" them accordingly.  I believe I have it figured out though.  Basically, I'm making use of `treeview.$parent.myMoveMethod` since the context of the exposed `drop` method doesn't have direct access to `this` in the context of the parent.

Contrast that with `item-clicked` where it is exposed to the current context.  It would be nice if this were the case natively.

**Comment by zdy1988** [comment]
hi ! @humblecoder 

i added that :

```
**@item-drop-before(node, item, draggedItem, e)**
```

```
    itemDropBefore (node, item, draggedItem , e) {
              if (!draggedItem) {
                  item.addChild({
                      text: "newNode",
                      value: "newNode"
                  })
              }
          },
```

it's maybe help you!  and you can see the [example](https://zdy1988.github.io/vue-jstree/)

**Comment by zdy1988** [comment]
please download the new version 2.1.1

**Comment by humblecoder** [comment]
Works great!  Thanks!
