### ISSUE TITLE
Exposure of drag/drop events unclear

### ISSUE THREAD

**Issue by humblecoder** [zdy1988/vue-jstree#35]
From looking at the source, I can see that `item-click` is accessible.  I can even access `drop`  However, I would also think that `item-drag-start` (or `drag-start`) and the like would be exposed.  Please explicitly state all exposed events.  If there are only the few listed, please expose more.

Primary use case I need to solve involves updating folder hierarchy on the server.  While I can acquire the target folder, I need to know what item is being dragged and dropped.  I suppose I could work around it by looking inside the target folder then calling `update` for every contained folder, but that seems a terrible solution.

**Comment by humblecoder** [comment]
Ok, yeah, drag and drop is completely unpredictable as far as data passed.  I have a `mousedown` that I use to set `currently_dragging_folder` (since I see no documented way to get the result of a drop).  However, it doesn't consistently trigger or set the `currently_dragging_folder`.  Please advise.

**Comment by zdy1988** [comment]
hi !  @humblecoder 

i publish new version to add that events :

```
@item-drag-start(node, item, e)

@item-drag-end(node, item, e)

@item-drop(node, item, draggedItem, e)

node : current node vue object
item : current node data item object 
e : event
```

please download version 2.1.0

**Comment by humblecoder** [comment]
@zdy1988 perfect, thanks!

**Comment by humblecoder** [comment]
@zdy1988 Actually, would you mind exposing all events including `contextmenu`?

**Comment by zdy1988** [comment]
a friend has asked the same question.
but i think there are other friends who want to register other events.
so i do it !
