### ISSUE TITLE
When I drag items, errors occur. How can I solve this? Error text "Cannot read property 'parentItem' of null"

### ISSUE THREAD

**Issue by zuxriddinkamalov** [zdy1988/vue-jstree#4]

**Comment by zdy1988** [comment]
Hi !

Make sure that your data contains the 'children' field?

same as the test data!

or  ... show me your code... browser version?

**Comment by zuxriddinkamalov** [comment]
data () {
    return {
      data: [
        {
          'text': 'Same but with checkboxes',
          'icon': 'fa fa-warning icon-state-danger',
          'children': [
            {
              'text': 'initially selected',
              'selected': true
            },
            {
              'text': 'custom icon',
              'icon': 'fa fa-warning icon-state-danger'
            },
            {
              'text': 'initially open',
              'icon': 'fa fa-folder icon-state-default',
              'opened': true,
              'children': [
                {
                  'text': 'Another node'
                }
              ]
            },
            {
              'text': 'custom icon',
              'icon': 'fa fa-warning icon-state-warning'
            },
            {
              'text': 'disabled node',
              'icon': 'fa fa-check icon-state-success',
              'disabled': true
            }
          ]
        },
        {
          'text': 'Same but with checkboxes',
          'opened': true,
          'children': [
            {
              'text': 'initially selected',
              'selected': true
            },
            {
              'text': 'custom icon',
              'icon': 'fa fa-warning icon-state-danger'
            },
            {
              'text': 'initially open',
              'icon': 'fa fa-folder icon-state-default',
              'opened': true,
              'children': [
                {
                  'text': 'Another node'
                }
              ]
            },
            {
              'text': 'custom icon',
              'icon': 'fa fa-warning icon-state-warning'
            },
            {
              'text': 'disabled node',
              'icon': 'fa fa-check icon-state-success',
              'disabled': true
            }
          ]
        },
        {
          'text': 'And wholerow selection'
        }
      ]
    }
  }
---------------------------------------------------------------------
<v-jstree :data="data" :draggable="true" allow-batch whole-row @item-click="itemClick"></v-jstree>

**Comment by zdy1988** [comment]
sorry, I can't recreate this bug !! 
v-jstree need to close!
```
<v-jstree></v-jstree>
```
other no problem !
v-jstree last version 1.0.7
i use vue's version 2.3.3
