### ISSUE TITLE
Performace

### ISSUE THREAD

**Issue by abernov** [zdy1988/vue-jstree#40]
[To my example i added performance test](https://jsfiddle.net/abernov/8ak4a1rq/)

Use my example to check performance

1) click on Folder1 then add 1000 files to it, click '-'
2) click on Folder2 then add 1000 files to it, click '-'
3) Right click on Folder3 and add one file

click +/- of Folder3  - get big delay! Why? There is only one file!
What is calculated so long?

**Comment by abernov** [comment]
I presume that this is the unlimited recursion throughout all the tree

**Comment by zdy1988** [comment]
thanks , you are right again !!! 

by testing, I found that there were two pieces of code that had problems.

```
          handleRecursionNodeParents(node, func) {
              if (node.$parent) {
                  if (func(node.$parent) !== false) {
                      this.handleRecursionNodeParents(node.$parent, func)
                  }
              }
          },
```

and

```
          handleSetGroupMaxHeight () {
              if (this.$refs.group) {
                  this.$refs.group.style.maxHeight = this.handleGroupMaxHeight() + 'px'
              }
              var self = this
              this.$nextTick(() => {
                  this.handleRecursionNodeParents(self, node => {
                      if (node.$refs.group) {
                          node.$refs.group.style.maxHeight = node.handleGroupMaxHeight() + 'px'
                      }
                  })
              })
          },
```

They trigger each other , when the tree has 100 nodes ,  it will trigger 10000 , has 1000 nodes , tigger 1000 * 1000

but  i rewrite it at new version , and added a new property **allow-transition**  to disable transition

**Comment by abernov** [comment]
I apologize, I updated my example to 2.1.5.

Nothing changed!

Please, add description for **allow-transition**.  What does it do?

**Comment by abernov** [comment]
For perfomance by default (if not set) must be
`item.dropDisabled = true,`

Because the number of files is always greater than the number of folders

I understand that those who already use your module, will have to change their code.
But the size of the data in the memory will be reduced, what is important with a large number of files

**Comment by zdy1988** [comment]
**allow-transition** is allow use transition animation, default is true

and **dropDisabled ** It only works if you drag and drop , that is set **draggable = "true"** ,  **dropDisabled ** is that disabled drop , default is 'undefined'   ,  =  false .

**Comment by abernov** [comment]
**dropDisabled ** is that disabled drop , default must be is 'undefined' , = **true** .

Because the number of files is always greater than the number of folders

**Comment by zdy1988** [comment]
when user set use draggable  , its global .
i can't just set the some nodes  disable drag.
If you need , you can disable it, it doesn't mean that other users don't.
this is the user to choose whether to disable.
by default, it should not be disabled.

**Comment by abernov** [comment]
Ok - drag disable - not the most important issue now.

The most important thing is:

[My example performance test](https://jsfiddle.net/abernov/8ak4a1rq/)

click +/- of Folder3  - get big delay! Why? There is only one file!
What is calculated so long?

**new version 2.1.6 did not solve the problem**
