### ISSUE TITLE
后台load数据的问题

### ISSUE THREAD

**Issue by jaja6** [zdy1988/vue-jstree#41]
我后台load数据到data中的一个list，然后照着demo写了，数据是帮上去了，但是点击事件都没了，如果我用后来load的json数据直接写到data里，就没有这个问题，能帮忙看看吗

**Comment by zdy1988** [comment]
你使用的是异步加载，还是直接设置的 data ，如果可以你贴一段代码上来，不然我猜不出来

我的例子里，两种加载方式可以点击的

**Comment by jaja6** [comment]
<template>

  <div class="mod-config">
    <el-form :inline="true" :model="dataForm" @keyup.enter.native="getDataList()">
      <el-form-item>
        
        <el-button v-if="isAuth('component:component:save')" type="primary" @click="addComponentHandler()">新增组件</el-button>
        <el-button v-if="isAuth('component:component:save') && addElementBtnVisible" type="primary" @click="addElementObjHandler()">新增组件对象</el-button>        
      </el-form-item>
    </el-form>
    <el-container style="height: auto; ">
  <el-aside width="300px" style="background-color: white;">
      <el-form :model="dataForm"  ref="dataForm" @keyup.enter.native="dataFormSubmit()" label-width="0px">
      </el-form>
  </el-aside>  
  <el-container>   
    <el-main>
      <v-jstree :data="treeList"   no-dots show-checkbox multiple allow-batch whole-row ref="jsTREE"	 ></v-jstree>
      <UpdateComponent v-if="updateComponentCtrlVisible" ref="UpdateComponent" @refreshDataList="getDataList"  ></UpdateComponent>      
    </el-main>
  </el-container>
</el-container>  
    <AddComponent v-if="addComponentCtrlVisible" ref="AddComponent" @refreshDataList="getDataList"></AddComponent>
    <AddElementObj v-if="addElementCtrlVisible" ref="AddElementObj" @refreshDataList="getDataList"></AddElementObj>
  </div>
</template>

<script>
  import API from '@/api'  
  import AddComponent from './component-action/component-add'
  import UpdateComponent from './component-action/component-update'
  import AddElementObj from './element-action/element-add'
  import { treeDataTranslate} from "@/utils";
  import ComponentTreeView from '@/components/component-tree/treeview'
  import VJstree from 'vue-jstree'

  export default {
    data () {
      return {
        treeList: [],
        treeListTreeProps: {
          label: "nodeName",
          children: "children"
        },
        tempKey: -666666,
        dataForm: {
          key: ''
        },
        dataListLoading: false,
        //component
        addComponentCtrlVisible: false,        
        updateComponentCtrlVisible: false,
        //element object
        addElementBtnVisible: false,
        addElementCtrlVisible: false,
        updateElementCtrlVisible: false,
        //treenode
        selectedNode: null,
        treeList1 : treeDataTranslate([{"nodeId":1,"nodeUuid":"272afa6d-4688-11e8-8a82-a08cfd3168d3","nodeName":"Lvl-1","nodeType":"category","parentId":0,"parentUuid":"root","parentName":"","iconName":"category"},{"nodeId":4,"nodeUuid":"aa1f6a74-c15f-45e5-b575-906364f2d524","nodeName":"lvl-1-1","nodeType":"category","parentId":1,"parentUuid":"272afa6d-4688-11e8-8a82-a08cfd3168d3","parentName":"","iconName":"category"},{"nodeId":17,"nodeUuid":"61b24b65-5d54-40d9-9b6f-7059398fb91c","nodeName":"lvl2","nodeType":"category","parentId":0,"parentUuid":"root","parentName":"","iconName":"category"},{"nodeId":18,"nodeUuid":"576b85c8-ed74-4c09-aae7-4532b0794c14","nodeName":"12312","nodeType":"category","parentId":4,"parentUuid":"aa1f6a74-c15f-45e5-b575-906364f2d524","parentName":"","iconName":"category"},{"nodeId":16,"nodeUuid":"db74fe83-14bd-4343-b749-ccc797173d77","nodeName":"公共登录组件","nodeType":"component","parentId":1,"parentUuid":"272afa6d-4688-11e8-8a82-a08cfd3168d3","parentName":"","iconName":"page"},{"nodeId":17,"nodeUuid":"8060baf7-2dc8-4c44-b3bf-a4851c63890f","nodeName":"dem1","nodeType":"component","parentId":4,"parentUuid":"aa1f6a74-c15f-45e5-b575-906364f2d524","parentName":"","iconName":"page"},{"nodeId":1,"nodeUuid":"9793e2df-b56c-4784-9361-7d49a39f04a8","nodeName":"用户名","nodeType":"textbox","parentId":16,"parentUuid":"db74fe83-14bd-4343-b749-ccc797173d77","parentName":"","iconName":"textbox"}],"nodeUuid","parentUuid")
      }
      
    },
    components: {
      AddComponent,
      UpdateComponent,
      ComponentTreeView,
      AddElementObj,
      VJstree
    },
    activated () {
      this.getDataList()
    },
    methods: {
      // 获取数据列表
      getDataList () {
        this.dataListLoading = true
        var params = {
          page: this.pageIndex,
          limit: this.pageSize,
          key: this.dataForm.key
        }
        API.component.getTree(params)
        .then(({data})=>{          
          this.treeList = treeDataTranslate(data.items, "nodeUuid","parentUuid")
          //this.treeList1 = treeDataTranslate([{"nodeId":1,"nodeUuid":"272afa6d-4688-11e8-8a82-a08cfd3168d3","nodeName":"Lvl-1","nodeType":"category","parentId":0,"parentUuid":"root","parentName":"","iconName":"category"},{"nodeId":4,"nodeUuid":"aa1f6a74-c15f-45e5-b575-906364f2d524","nodeName":"lvl-1-1","nodeType":"category","parentId":1,"parentUuid":"272afa6d-4688-11e8-8a82-a08cfd3168d3","parentName":"","iconName":"category"},{"nodeId":17,"nodeUuid":"61b24b65-5d54-40d9-9b6f-7059398fb91c","nodeName":"lvl2","nodeType":"category","parentId":0,"parentUuid":"root","parentName":"","iconName":"category"},{"nodeId":18,"nodeUuid":"576b85c8-ed74-4c09-aae7-4532b0794c14","nodeName":"12312","nodeType":"category","parentId":4,"parentUuid":"aa1f6a74-c15f-45e5-b575-906364f2d524","parentName":"","iconName":"category"},{"nodeId":16,"nodeUuid":"db74fe83-14bd-4343-b749-ccc797173d77","nodeName":"公共登录组件","nodeType":"component","parentId":1,"parentUuid":"272afa6d-4688-11e8-8a82-a08cfd3168d3","parentName":"","iconName":"page"},{"nodeId":17,"nodeUuid":"8060baf7-2dc8-4c44-b3bf-a4851c63890f","nodeName":"dem1","nodeType":"component","parentId":4,"parentUuid":"aa1f6a74-c15f-45e5-b575-906364f2d524","parentName":"","iconName":"page"},{"nodeId":1,"nodeUuid":"9793e2df-b56c-4784-9361-7d49a39f04a8","nodeName":"用户名","nodeType":"textbox","parentId":16,"parentUuid":"db74fe83-14bd-4343-b749-ccc797173d77","parentName":"","iconName":"textbox"}],"nodeUuid","parentUuid")
        })
        this.dataListLoading = false
      },     
      addComponentHandler (id) {
        this.addComponentCtrlVisible = true
        this.$nextTick(() => {
          this.$refs.AddComponent.init(id)
        })
      },      
      treeNodeSelectedHandler(node)
      {
        this.selectedNode = node
        if(node.nodeType !== "category"){
          this.addElementBtnVisible = false
        }
        else{
          this.addElementBtnVisible = true
        }
        if(node.nodeType === "component")        
        this.updateComponentHandler(node)
      },
      updateComponentHandler(node){        
        if(node.nodeId === 0 || node.nodeType === "category"){
          this.updateComponentCtrlVisible = false;
        }
        else{
          this.updateComponentCtrlVisible = true;
          this.$nextTick(()=>{
            this.$refs.UpdateComponent.init(node.nodeId)
          })
        }          
      },
      addElementObjHandler(){
        this.addElementCtrlVisible = true
        this.addComponentCtrlVisible = false
        console.log(this.selectedNode)
        this.$nextTick(() => {
          this.$refs.AddElementObj.init(this.selectedNode.nodeType, this.selectedNode.nodeId, 
            this.selectedNode.nodeUuid, this.selectedNode.nodeName)
        })
      },
      itemclick(node){
        console.log(node)
      }
    }
  }
</script>


上面是我的代码，其中如果将数据源替换为treeList1没有问题，但是如果直接treeList绑定，就不行

**Comment by jaja6** [comment]
源码有点大，我放附件中了。
我的问题是，如果我绑定的是treeList1没有问题，可以展开，可以点击。但是如果我绑的是treeList, 是通过API获得的完整的数据的话，页面会显示第一层的两个节点，但是不能展开，不能点击。我看了页面元素，group里已经有相面的节点了，就是没有效果。index.js是将数据转换成层级结构的数据。
谢谢啦

[Desktop.zip](https://github.com/zdy1988/vue-jstree/files/1946827/Desktop.zip)

**Comment by jaja6** [comment]
我试了下，好像放在then里面就不行

**Comment by jaja6** [comment]
我试了下，将treeList1赋值的语句放到getDataList方法开头就可以，放在then里就不行，请问怎么处理呢?

**Comment by zdy1988** [comment]
嗯，是这样的
是因为树在初始化的时候会将数据做一次初始化
就是 你的节点数据即使是 { text: 'text1' } ，我会自动将节点数据初始化成 {text: 'text1', value: 'text1' ,opened:  false ...等等}
你在获取了数据列表，直接赋值data时，组件获取不到 opened 或者 selected 的状态信息，所以失效了，
你可以尝试用我提供的方法，初始化一下你的数据

this.treeList = this.$refs.tree.initializeData( **yourdata** ) 

不过我觉得这么做不太好，你最好还是用**async**来load你的数据

**Comment by jaja6** [comment]
谢谢回复，已经可以用了。我想再问下，我的树root也是可能多个节点，用async也可以吗?

**Comment by zdy1988** [comment]
root的个数取决于你第一级数据的个数，就像我的例子 **async loading** 中，我首次加载了两个节点

**Comment by jaja6** [comment]
谢谢

**Comment by nick-running** [comment]
真的难用，已经放弃了，问题多多
