### ISSUE TITLE
EVENTS onBeforeNodeOpen, onAfterNodeClosed

### ISSUE THREAD

**Issue by abernov** [zdy1988/vue-jstree#42]
Please add events:

onBeforeNodeOpen(node) - on click "+"
onAfterNodeClosed(node) - on click "-"

onBeforeNodeOpen - i will load node children from database to tree (If several users simultaneously work with the tree,  need to update the children before open the node)
onAfterNodeClosed - i will delete node children and create one fake child for "+" was visible

This will solve the performance problem - because the total number of nodes in the tree will decrease.

**Comment by zdy1988** [comment]
if so , you can use **onItemToggle** and **async** load the data
