### ISSUE TITLE
how to get all selecte id?no api?

### ISSUE THREAD

**Issue by BourneSuper** [zdy1988/vue-jstree#52]
hi,
how to get all selecte id?no api?

**Comment by zdy1988** [comment]
#9

**Comment by BourneSuper** [comment]
@zdy1988 
I follwed #9 ,but something went wrong.--TypeError: Cannot read property 'selected' of undefined

`<v-jstree ref="tree" :data="data" show-checkbox multiple allow-batch whole-row @item-click="itemClick" ></v-jstree>`
`    	            this.selectedItems = [];
    	            this.$refs.tree.handleRecursionNodeChilds(this.$refs.tree, node => {
    	            	console.log(node);
    	              if (node.model.selected) {
    	                this.selectedItems.push(node.model.id)
    	              }
    	            })
    	            console.log(selectedItems);`

the node argument don't have model

**Comment by zdy1988** [comment]
sorry ! I forgot to tell you !

root node has no **model**

so 

`if (node.model && node.model.selected)`

**Comment by BourneSuper** [comment]
@zdy1988  Thanks.
