### ISSUE TITLE
@item-toggle, event never fired

### ISSUE THREAD

**Issue by cdubant** [zdy1988/vue-jstree#7]
Thanks for this fantastic plugin integration for Vue 2.0.

The plugin is working fine and as expected, I only have 2 questions (things that I cant' achieve)

- Detect when an unselected node is toggled (expanded / collapsed) as I need to store the opened / closed state of nodes. Tried @item-toggle="itemToggle" as @item-click is working fine but I didn't succeed, it does nothing even with a console.log inside to see if it goes through the function (my assumption is the function is never called and the event onItemToggle is never fired

- I want to send a node deletion command to the tree using Vue 2.0 (and also rename the node) as I created buttons to create new nodes (works fine), delete an existing node (undone for the moment), rename a node (undone for the moment).

Any help would be greatly appreciated and at the end I'll be able to share a full example with more capabilities than the current documentation.

Thanks in advance.

**Comment by zdy1988** [comment]
very thanks for your issues!

i published a new version !

Look at this [example](http://zdy1988.github.io/vue-jstree), whether it can be

**Comment by cdubant** [comment]
Hi Zhu,

I checked your example and it looks fine so with it I should be able to delete a node properly from the tree.

Nevertheless, you should also publish the source code of the example you have mentioned.

And it doesn't answer the need for renaming a node and detecting when a node has been opened or closed.

How would you do it using Vue 2.0?

**Comment by zdy1988** [comment]
Hi ! 

i use vue's version 2.3.3

- the node item data is **two-way** binding , so you can renaming the node directly
- **opened** field is the toggle state , you can watch **opended** in node data

**Comment by cdubant** [comment]
Zhu,

In tree.vue it looks like OnItemClick emits an event like this
this.$emit('item-click', oriNode, oriItem)

If you take a look at OnItemToggle, there is no event emitted.

Would you consider making this available for detecting open/close event on tree?

**Comment by cdubant** [comment]
Zhu,

I modified the code of tree.vue locally as I don't know how to create a Pull Request but I found the modification I wanted to have.

In tree.vue, simply add this.$emit("item-toggle" oriNode, oriItem) inside OnItemToggle to make it look like this

`onItemToggle (oriNode, oriItem) {
        if (oriNode.model.opened) {
          this.handleAsyncLoad(oriNode.model.children, oriNode, oriItem)
        }
        this.$emit('item-toggle', oriNode, oriItem)
      },`

**Comment by zdy1988** [comment]
Oh! Now I understand.
