### ISSUE TITLE
get selected items ids

### ISSUE THREAD

**Issue by farhadf246** [zdy1988/vue-jstree#9]
**hi thanks for update it's very use full.** 

can you help me to get array of selected ids?

like this:
{1,23,43,12}

**Comment by zdy1988** [comment]
hi , you can get array like this :

```
        this.selectedItems = []
        this.$refs.tree.handleRecursionNodeChilds(this.$refs.tree, node => {
          if (node.model.selected) {
            this.selectedItems.push(node.model.id)
          }
        })
```

the method **handleRecursionNodeChilds** can help you recursion tree node !

**Comment by farhadf246** [comment]
thank you so much!
its work fine.

**Comment by jktnavy** [comment]
Hi, Kindly need your help.

I following your instruction before, there are show error when I compile ?

```
			this.selectedItems = [];
			this.$refs.tree.handleRecursionNodeChilds(this.$refs.tree, node => {
				// console.log(node);
				if (node.model && node.model.selected) {
					this.selectedItems.push(node.model.id)
				}
			});
			console.log(selectedItems);
```

![image](https://user-images.githubusercontent.com/70367218/102448372-91aeee80-4064-11eb-802f-01fbb8c3dfeb.png)
